# Generated by Django 3.0.5 on 2023-12-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='conform_password',
            new_name='confirm_password',
        ),
    ]
